/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 macaw.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/macaw.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="container" position={[0.025, -1.854, 0]} scale={0.3}>
          <group name="bird" position={[-0.084, 6.179, 0]} scale={3.333}>
            <primitive object={nodes.base} />
            <skinnedMesh name="BODY" geometry={nodes.BODY.geometry} material={materials.material} skeleton={nodes.BODY.skeleton} />
            <skinnedMesh name="Cornea_L" geometry={nodes.Cornea_L.geometry} material={materials.cornea} skeleton={nodes.Cornea_L.skeleton} />
            <skinnedMesh name="Cornea_R" geometry={nodes.Cornea_R.geometry} material={materials.cornea} skeleton={nodes.Cornea_R.skeleton} />
            <skinnedMesh name="cover_feather" geometry={nodes.cover_feather.geometry} material={materials.material} skeleton={nodes.cover_feather.skeleton} />
            <skinnedMesh name="Eye_L" geometry={nodes.Eye_L.geometry} material={materials.material} skeleton={nodes.Eye_L.skeleton} />
            <skinnedMesh name="Eye_R" geometry={nodes.Eye_R.geometry} material={materials.material} skeleton={nodes.Eye_R.skeleton} />
            <skinnedMesh name="FILM_L_1" geometry={nodes.FILM_L_1.geometry} material={materials.material} skeleton={nodes.FILM_L_1.skeleton} />
            <skinnedMesh name="FILM_R_1" geometry={nodes.FILM_R_1.geometry} material={materials.material} skeleton={nodes.FILM_R_1.skeleton} />
            <skinnedMesh name="tail_feathers" geometry={nodes.tail_feathers.geometry} material={materials.material} skeleton={nodes.tail_feathers.skeleton} />
            <skinnedMesh name="Wings" geometry={nodes.Wings.geometry} material={materials.material} skeleton={nodes.Wings.skeleton} />
            <skinnedMesh name="Wings001" geometry={nodes.Wings001.geometry} material={materials.material} skeleton={nodes.Wings001.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/macaw.glb')
